### ISSUE TITLE
Documentation and possible contribution markdown file

### ISSUE THREAD

**Issue by Gann4Life** [EyeOdin/project_pages#2]
I'd like to contribute to this plugin, however I'm unsure how to get started or what conventions are being used for this. I know for sure that there are some tools I need to investigate on my own like using Qt, but I'm looking for a place to start mostly, this information is often in a CONTRIB.md file

EDIT: I would also like to know example use cases for the properties shown in the wiki, I feel that what's written is not enough to be able to understand

**Comment by EyeOdin** [comment]
I have tried to work in the past with other people and I did not manage to make things work properly so I ended up just making sure I can garanty to give the eyeodin seal of quality when I make stuff. So I mostly do stuff solo at the moment.

However if you are interested you can do a Fork of the project and try and do your custom version it just needs to respect the GNU GPL license as that would carry over due to the Qt modules.

If I will accept the fork into main I am not sure as I follow coding principals that do not match normal standards. I came to fall on these principals due to trail and error and they seem to work the best under these conditions, but always evolving the more I learn.
